name: frontend
# ワークフローの名前
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: aws s3 sync . s3://udemy-github-actions-s3-sawata --exact-timestamps --region ap-northeast-1
      